### ISSUE TITLE
HemoLearn cannot be installed due to error installing prox_tv dependency

### ISSUE THREAD

**Issue by eurunuela** [hemolearn/hemolearn#3]
Here's the error:

```bash
Building wheel for prox_tv (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6z/7w14fjc11bs572r6b50rqqf40000gn/T/pip-install-cj400kgx/prox-tv_7db48e3580ad4aa3a0a946ba5f0405f7/setup.py", line 4, in <module>
          setup(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/installer.py", line 102, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/wheel.py", line 117, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/6z/7w14fjc11bs572r6b50rqqf40000gn/T/pip-install-cj400kgx/prox-tv_7db48e3580ad4aa3a0a946ba5f0405f7/.eggs/cffi-1.15.1-py3.8-macosx-11.0-arm64.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/6z/7w14fjc11bs572r6b50rqqf40000gn/T/pip-install-cj400kgx/prox-tv_7db48e3580ad4aa3a0a946ba5f0405f7/.eggs/cffi-1.15.1-py3.8-macosx-11.0-arm64.egg/EGG-INFO'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for prox_tv
  Running setup.py clean for prox_tv
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6z/7w14fjc11bs572r6b50rqqf40000gn/T/pip-install-cj400kgx/prox-tv_7db48e3580ad4aa3a0a946ba5f0405f7/setup.py", line 4, in <module>
          setup(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/installer.py", line 102, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/wheel.py", line 117, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/6z/7w14fjc11bs572r6b50rqqf40000gn/T/pip-install-cj400kgx/prox-tv_7db48e3580ad4aa3a0a946ba5f0405f7/.eggs/cffi-1.15.1-py3.8-macosx-11.0-arm64.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/6z/7w14fjc11bs572r6b50rqqf40000gn/T/pip-install-cj400kgx/prox-tv_7db48e3580ad4aa3a0a946ba5f0405f7/.eggs/cffi-1.15.1-py3.8-macosx-11.0-arm64.egg/EGG-INFO'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for prox_tv
  Building wheel for lxml (setup.py) ... done
  Created wheel for lxml: filename=lxml-4.9.2-cp38-cp38-macosx_11_0_arm64.whl size=1607707 sha256=3c551d62d0a8621ce3c47916a23127d31b3a67fc4d360d921b449e0f4bf1fca6
  Stored in directory: /Users/eurunuela/Library/Caches/pip/wheels/7d/07/7c/a945c6121e40f34b64fc7f8bdd88dd811c0ac1d8a3884b79de
Successfully built hemolearn lxml
Failed to build prox_tv
Installing collected packages: pytz, zipp, urllib3, threadpoolctl, six, pyparsing, pycparser, pillow, packaging, numpy, lxml, llvmlite, kiwisolver, joblib, idna, fonttools, cycler, charset-normalizer, certifi, scipy, requests, python-dateutil, nibabel, importlib-resources, importlib-metadata, contourpy, cffi, scikit-learn, prox_tv, pandas, numba, matplotlib, nilearn, hemolearn
  Running setup.py install for prox_tv ... error
  error: subprocess-exited-with-error

  × Running setup.py install for prox_tv did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      /Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running install
      /Users/eurunuela/conda_envs/hemolearn/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-38
      creating build/lib.macosx-11.0-arm64-cpython-38/prox_tv
      copying prox_tv/__init__.py -> build/lib.macosx-11.0-arm64-cpython-38/prox_tv
      copying prox_tv/prox_tv_build.py -> build/lib.macosx-11.0-arm64-cpython-38/prox_tv
      copying prox_tv/prox_tv_test.py -> build/lib.macosx-11.0-arm64-cpython-38/prox_tv
      running build_ext
      generating cffi module 'build/temp.macosx-11.0-arm64-cpython-38/_prox_tv.cpp'
      creating build/temp.macosx-11.0-arm64-cpython-38
      building '_prox_tv' extension
      creating build/temp.macosx-11.0-arm64-cpython-38/build
      creating build/temp.macosx-11.0-arm64-cpython-38/build/temp.macosx-11.0-arm64-cpython-38
      creating build/temp.macosx-11.0-arm64-cpython-38/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/eurunuela/conda_envs/hemolearn/include -arch arm64 -fPIC -O2 -isystem /Users/eurunuela/conda_envs/hemolearn/include -arch arm64 -DNOMATLAB=1 -I/Users/eurunuela/conda_envs/hemolearn/include/python3.8 -c build/temp.macosx-11.0-arm64-cpython-38/_prox_tv.cpp -o build/temp.macosx-11.0-arm64-cpython-38/build/temp.macosx-11.0-arm64-cpython-38/_prox_tv.o -Isrc
      In file included from build/temp.macosx-11.0-arm64-cpython-38/_prox_tv.cpp:570:
      In file included from src/TVopt.h:15:
      src/general.h:22:10: fatal error: 'lapacke.h' file not found
      #include <lapacke.h>
               ^~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> prox_tv

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by hemolearn** [comment]
Hi @eurunuela ,

Thx for the reporting!

What OS are you using and how do you install it? (MacOS / Conda, right ?) Can you give the exact command line?

It seems that prox_tv is difficult to install on MacOS. Did you take a look at Issue 12 of the corresponding Github: https://github.com/albarji/proxTV/issues/12 ? Can you try this fork for prox_tv

**Comment by eurunuela** [comment]
I tried following the installation instructions on the HemoLearn docs but they assume dependencies are already installed (I saw you do not have the dependencies in your setup file). So I had to `pip install` every dependency one by one as I saw `python setup.py install` fail with a new missing dependency.

The error reported above happens both on my MacOS and the high-performance computing system we have at BCBL that runs on Linux. In both cases, I use a conda environment.

In any case, issue 12 was solved by [PR #15](https://github.com/albarji/proxTV/pull/15), which was merged into `master` 3 years before the last pipy release was made. Surely, this fix should be on the version I'm trying to install from pipy (i.e., the latest).

**Comment by hemolearn** [comment]
Hemolearn does not assumed that. The dependencies of Hemolearn are fetched from the `info.py` (with a fix to be done on Scikit-Learn installation btw). However, we could add a requirement.txt to ease that part if needed.

So you told me that you did `python3 -m pip install --user prox_tv` on your MacOS and 'a Linux'  within a Conda env, right?

Indeed https://github.com/albarji/proxTV/pull/15 was merged, but have you read that they "_Added the path to find lapacke.h (at least for those that have openblas installed via homebrew)_." in this PR?

As, your traceback said: `src/general.h:22:10: fatal error: 'lapacke.h' file not found` I think it's your problem.

The short answer here is: 'you need LAPACK to install prox_tv'. Use `apt policy` to check if it's installed.

If it's not enough, the lead to explore is: how your clang / gnu compiler manage their LAPACK dependencies.

**Comment by eurunuela** [comment]
Thank you for the feedback!

> Hemolearn does not assumed that. The dependencies of Hemolearn are fetched from the info.py (with a fix to be done on Scikit-Learn installation btw). However, we could add a requirement.txt to ease that part if needed.

I think that would make it easier for users.

> So you told me that you did python3 -m pip install --user prox_tv on your MacOS and 'a Linux' within a Conda env, right?

Correct.

> Indeed https://github.com/albarji/proxTV/pull/15 was merged, but have you read that they "Added the path to find lapacke.h (at least for those that have openblas installed via homebrew)." in this PR?

I did. I also tried after installing `openblas` with homebrew but I had the same issue.

> If it's not enough, the lead to explore is: how your clang / gnu compiler manage their LAPACK dependencies.

I'm going to have to ask our IT department to install it for me as it looks like I don't have the necessary permissions to do it myself.

I will keep you posted. Thank you once again.

**Comment by hemolearn** [comment]
You need to install _Linear Algebra PACKage LAPACK_ not _OpenBLAS_ (which use it). Something like this should do the trick: `brew install lapack`. Can you try this and tell me if it works on your laptop?

In any case, since it seems that you have an installation problem with _LAPACK_ needed for `prox_tv`, may be those pointers would be more pertinent for you:
https://github.com/albarji/proxTV/issues  for `prox_tv`
https://stackoverflow.com/questions/38114201/installing-lapack-and-blas-libraries-for-c-on-mac-os for `Lapack `(if the comment on `veclib `is still relevant)

Once you have all the dependencies set, run the HemoLearn install and launch the tests, tell me if it works fine.

Best

**Comment by eurunuela** [comment]
I finally managed to install it and run it. Apparently, LAPACK is not accessible from conda environments in our high-performance computing server.

Thank you for the help!
